# Site settings
title: Ivelin Yanev
twitter_username: iqnev
name: Ivelin Yanev

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/iqnev
 - title: LinkedIn
   url: https://www.linkedin.com/in/ivelin-yanev-37491544/

#Any buzzword skills you want to include
skills:
 - Java
 - C/C++
 - Embedded
 - Linux
 - Android
 - Electronics
 - Robotics
 - IoT Architecture

#Work experience is required
roles:
 - title: Software Developer
   start: 2011
   end:   2012
   employer: eComDev Studio Ltd.
   description: Payment Gateway applications
   
 - title: CTO
   start: 2012
   end:   2013
   employer: Zine Ltd.
   description: Start up project- online systems for research.
   
 - title: Software Developer
   start: 2013
   end:   2015
   employer: eService Ltd.
   description: Medical Software Development.
   
 - title: Embedded Java Engineer
   start: 2015
   end:   2015
   employer: ProSyst - Bosch Group.
   description: Embedded Solutions, Smart Home, OSGI, Z-Wave.
  
 - title: Software Engineer
   start: 2016
   end:   Ongoing
   employer: Software Engineer.
   description: Platform team.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   subject: Computer science and technologies
   school: Technical University of Varna
   
 - level: Master of Science (MSc)
   subject: Computer Software Engineering
   school: Technical University of Varna

#This section is optional (as is the image link below)
coursera:
   courses:
    - title: University of Maryland, Programming Mobile Applications for Android Handheld Systems
      link: https://www.coursera.org/learn/android-programming
      optionalimage: https://www.oneclickroot.com/wp-content/uploads/2013/12/university-of-maryland.png
    - title: Princeton University, Algorithms: Part 1 Part 2, Part 3
      link: https://www.coursera.org/learn/algorithms-part1
      optionalimage: https://s-media-cache-ak0.pinimg.com/236x/23/a7/f7/23a7f74c05d762db7d180e8b2665aef0.jpg
    - title: Vanderbilt University, Pattern-Oriented Software Architectures for Concurrent and Networked Software
      optionalimage: https://news.vanderbilt.edu/files/schmidt-title1-600x350.png
    - title: University of Washington, The Hardware/Software Interface
      link: https://courses.cs.washington.edu/courses/cse351/
      optionalimage: https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/cbd86332a9e7.png

#List of interesting Github repo/projects to include - optional
github:
 - iqnev/parnik
 - iqnev/VineyardGuard
 - iqnev/SmartDevices
 - iqnev/SerialportHandler
 - iqnev/automatic_vacuum_cleaner
 - iqnev/complementary-filter
 - iqnev/motion-detection
 - iqnev/jvmstart
 - iqnev/Echo-Commands
 - iqnev/Pi4JDemos
 - iqnev/OSGi-basic
 - iqnev/CustomClassLoader
 - iqnev/ArdTest
 - iqnev/DesignPattern
 - iqnev/deultum
 - iqnev/tangra
 - iqnev/MPI
 